### ISSUE TITLE
Problemas al entregar

### ISSUE THREAD

**Issue by Lilneko** [papajoshh/CrazyBoxes-Repo#10]
1er caso:  Al coger la caja debajo de la portería de su color, se hace complicado entregar.
2º caso: Con las porterías móviles activas también hay veces que no la acepta aun moviendola contra la portería.

Sugerencia: Eliminar la zona de las porterías que entran dentro del área de juego, limitandolas a los bordes.

**Comment by papajoshh** [comment]
Esta issue se queda sólo con:
1er caso: Al coger la caja debajo de la portería de su color, se hace complicado entregar.

El error está en que cuando las cajas están pegadas a la portería no detecta que debe eliminarla al cogerla (esto es por un bug en a la hora de ejecutar los métodos por OnTriggerStay). Esto se podría eliminar moviendo las porterías del mismo modo que arreglando el bug. Al ser cosa de arte habría que hablarlo con María.
Para el segundo caso abro la [issue 11](https://github.com/papajoshh/CrazyBoxes-Repo/issues/11)

**Comment by papajoshh** [comment]
Esto está solucionado con el diseño de las cintas transportadoras. Cierro.
