### ISSUE TITLE
Diseño e implementación porteria

### ISSUE THREAD

**Issue by papajoshh** [papajoshh/CrazyBoxes-Repo#38]
Crear un arte menos básico para las porterías.

Habría que pensar en una idea (diseño y arte) que cuadre con la temática del juego de entregar cajas.

**Comment by Lilneko** [comment]
Cintas transportadoras, que salgan hacia los laterales de la pantalla

**Comment by papajoshh** [comment]
Diseño implementado. Pendiente de animaciones.

**Comment by papajoshh** [comment]
Esto está puesto como tarea de arte/programación.
