### ISSUE TITLE
La caja no se va por la cinta hasta que sueltas el dedo

### ISSUE THREAD

**Issue by Lilneko** [papajoshh/CrazyBoxes-Repo#55]
Aunque puntúa y sale la monedita, la caja no se va hasta que no la sueltas.

Debería:
O puntúa (y la animación de la monedita) al soltarla y que se vaya.
O en cuanto puntúa... se va..... tengas donde tengas el dedo....

**Comment by papajoshh** [comment]
Se ha puesto de modo que en cuanto suelte la moneda la caja sea absorbida. Probado. Cierro la issue.
