### ISSUE TITLE
Las cajas a veces no se van por la cinta y se quedan bloqueadas

### ISSUE THREAD

**Issue by Lew9** [papajoshh/CrazyBoxes-Repo#56]
En ocasiones las porterías no recogen la caja y esta se queda ahí plantada. Da feedback visual y de sonido pero son inamovibles, como si se convirtieran en cajas de metal.
![ezgif-5-b88eb7a219](https://user-images.githubusercontent.com/30477660/32745537-53082010-c8b3-11e7-949f-8524fa677a45.gif)

**Comment by Lew9** [comment]
Les afectan de manera normal la gravedad, las bombas y los boost 1 y 4.

**Comment by papajoshh** [comment]
Era por un problema al activar las físicas a true. Probado. Cierro.
