### ISSUE TITLE
Al subir una caja a la linea de warning, pierdes auto

### ISSUE THREAD

**Issue by Lilneko** [papajoshh/CrazyBoxes-Repo#72]
Solo funciona si la subes según empiezas la partida... se ve que tarda en ponerse en marcha el contador o tal.

**Comment by papajoshh** [comment]
El problema pasaba con las dos cajas del inicio. Al no pasar por la zona del game over no se las marcaba como"cajas in game" y el limite superior lanzaba el game over automático porque el código no pasaba por donde debía. Se han configurado las cajas para que estén directamente como "in game". Cierro
