### ISSUE TITLE
Marca de gameover confusa

### ISSUE THREAD

**Issue by Lilneko** [papajoshh/CrazyBoxes-Repo#8]
Actualmente esta demasiado alta fuera de pantalla y no visible. Es confuso ya que no se sabe cuando vas a perder.
Habría que recolocarla y mostrarla (diseño) como una portería, para mostrar mas intuitivamente que si tocan eso, se pierde.
Algo como una linea roja de puntos finita, o espiral roja, animada?

**Comment by papajoshh** [comment]
Bajo la línea roja cómo estaba antes. He subido corrección porque aunque la línea no se veía (estaba justo encima de donde acababa la pantalla) no estaba contando bien el tiempo que tenían que estar las cajas en la zona de game Over para perder.

Por mi parte soluciono, la línea roja es tema de María.

**Comment by Lilneko** [comment]
Recomiendo subir la linea de gameover hasta arriba del todo, pegado a la bar de Puntuación. Y de cara a diseño que ocupe aproximadamente la mitad de lo que es actualmente. Ya que su ancho no es relevante, y cuanto mas abajo esta mas invasiva es y mayor sensación de frustración da.

**Comment by papajoshh** [comment]
Diseño hecho e implementado
