### ISSUE TITLE
Ajustes en Cajas Spray y Bomba

### ISSUE THREAD

**Issue by Lilneko** [papajoshh/CrazyBoxes-Repo#9]
- Deberían poder moverse (sin detonar)
- Ampliar un poco el área al que afectan. Para que sean un poco mas tolerantes con los espacios y pieza colocadas irregularmente.

**Comment by papajoshh** [comment]
Se ha corregido esta parte. La detonación depende de cuando sueltes la bomba (se sentía raro si movías la bomba, la soltabas y tenías que clickar encima una vez soltada para detonarla).

Sube en la build de esta noche. La cierro, cualquier cosa reabrís
